### PR TITLE
Add `ffill`

### PR DESCRIPTION
**Pull request by max-sixty**
This is 2.7x the performance of pandas on large arrays (and 9x the performance on small arrays)

It's very small simple function.

Numba doesn't support object arrays, unfortunately, so this will only work on floats (ints aren't nullable).

Need to split out from https://github.com/numbagg/numbagg/pull/144

### CODE REVIEW

**Comment by dcherian** [comment]
Can we add this for the non-moving case too please?

**Comment by max-sixty** [comment]
> Can we add this for the non-moving case too please?

Like a `.fillna`? I am a bit doubtful we'll be faster than numpy for that, and we don't benefit from any gufunc-vectorization...

**Comment by dcherian** [comment]
There's no numpy version IIRC. Xarray implements it using `bottleneck.push`.

**Comment by max-sixty** [comment]
> There's no numpy version IIRC. Xarray implements it using `bottleneck.push`.

WDYM re moving vs. non-moving version?

I originally thought you might mean `.fillna` by non-moving, but `bn.push` is just for `.ffill`, which is here...

**Comment by dcherian** [comment]
doh! sorry for the noise. The `import` from `moving` confused me. This is great!

**Comment by max-sixty** [comment]
Yeah having it in `moving` was kinda confusing — it's not a window function. I've moved it so it's clearer...

**Pull request merged**
